- name: Configure Nginx
  hosts: web1
  become: yes
  vars:
    email: "{{ lookup('env','CERTBOT_EMAIL') }}"
    domain_name: "{{ lookup('env','DOMAIN_NAME') }}"
    server_build_path: "/var/www/{{ domain_name }}"
    nginx_sites_available: "/etc/nginx/sites-available"
    nginx_sites_enabled: "/etc/nginx/sites-enabled"
    api_port: "{{ lookup('env','API_PORT') }}"
    swagger_port: "{{ lookup('env','SWAGGER_PORT') }}"

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Install Certbot
      apt:
        name: [certbot, python3-certbot-nginx]
        state: present
        update_cache: yes

    - name: Check if SSL certificate exists before certbot
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: ssl_cert_before

    - name: Create HTTP Nginx config
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_sites_available }}/{{ domain_name }}-http"
      notify: Restart Nginx

    - name: Create symlink for HTTP config
      file:
        src: "{{ nginx_sites_available }}/{{ domain_name }}-http"
        dest: "{{ nginx_sites_enabled }}/{{ domain_name }}-http"
        state: link
      notify: Restart Nginx

    - name: Ensure Nginx is running before Certbot
      service:
        name: nginx
        state: started

    - name: Obtain SSL certificate via webroot
      command: >
        certbot certonly --webroot -w {{ server_build_path }}
        -n --agree-tos --email {{ email }} -d {{ domain_name }}
      when: not ssl_cert_before.stat.exists
      register: certbot_result
      failed_when: certbot_result.rc not in [0, 2]  # rc=2 if cert exists

    - name: Check if SSL certificate exists after Certbot
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      register: ssl_cert_after

    - name: Create HTTPS Nginx config if certificate exists
      template:
        src: nginx.conf.https.j2
        dest: "{{ nginx_sites_available }}/{{ domain_name }}"
      vars:
        ssl_exists: "{{ ssl_cert_after.stat.exists }}"
      when: ssl_cert_after.stat.exists
      notify: Restart Nginx

    - name: Create symlink for HTTPS config
      file:
        src: "{{ nginx_sites_available }}/{{ domain_name }}"
        dest: "{{ nginx_sites_enabled }}/{{ domain_name }}"
        state: link
      when: ssl_cert_after.stat.exists
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted